#########################################################
#       Aiidor Hardcore -  Version 2.0                  #
#                 Author : B. Goodes                    #
#########################################################

serveur-tag: "&6[&fAiidor&6] &r"
world: "world"

Money:
  devise: "Coins"
  start-balance: 100 
  
Guilds:
  guild-price: 500

  
  